[workspace]
resolver = "2"
members = [
    "MagnumProxy",
    "MagnumProxySSL",
    "Manager",
    "ConnectionsManager",
    "CheckUser"
]

[build]
rustflags = [
  "-C", "target-feature=-avx512f",
  "-C", "target-cpu=native"
]

